# Generated by Django 4.2.7 on 2025-11-14 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NRCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('new', 'New NRC'), ('replacement', 'Replacement')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('chief_name', models.CharField(max_length=100)),
                ('mother_village', models.CharField(max_length=100)),
                ('mother_date_of_birth', models.DateField()),
                ('mother_place_of_birth', models.CharField(max_length=100)),
                ('mother_chief_name', models.CharField(max_length=100)),
                ('father_village', models.CharField(max_length=100)),
                ('father_date_of_birth', models.DateField()),
                ('father_place_of_birth', models.CharField(max_length=100)),
                ('father_chief_name', models.CharField(max_length=100)),
                ('birth_certificate', models.FileField(upload_to='documents/birth_certificates/')),
                ('under_five_card', models.FileField(upload_to='documents/under_five_cards/')),
                ('old_nrc', models.FileField(blank=True, null=True, upload_to='documents/old_nrc/')),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
