# Generated by Django 4.2.7 on 2025-11-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_nrcapplication_father_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrcapplication',
            name='nrc_back_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nrcapplication',
            name='nrc_front_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nrcapplication',
            name='nrc_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrcapplication',
            name='nrc_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
