# Generated by Django 4.2.7 on 2025-12-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_nrcapplication_replacement_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrcapplication',
            name='digital_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True),
        ),
    ]
