# Generated by Django 4.2.7 on 2025-12-16 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detection_type', models.CharField(choices=[('exact_match', 'Exact Match'), ('similar_match', 'Similar Match'), ('user_existing_nrc', 'User Already Has NRC'), ('nrc_number_duplicate', 'NRC Number Duplicate')], max_length=50)),
                ('action_taken', models.CharField(choices=[('blocked', 'Application Blocked'), ('warned', 'Warning Issued'), ('approved_override', 'Admin Override Approved')], max_length=50)),
                ('attempted_application_data', models.JSONField()),
                ('matching_application_ids', models.JSONField(default=list)),
                ('similarity_scores', models.JSONField(default=list)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_duplication_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplication_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
