# Generated by Django 4.2.7 on 2025-12-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_duplicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_admin_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('nrc_ready', 'NRC Card Ready for Download'), ('new_application_submitted', 'New Application Submitted'), ('system_update', 'System Update')], max_length=50),
        ),
    ]
