# Generated by Django 4.2.7 on 2025-11-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_otp_code_customuser_otp_created_at_and_more'),
    ]

    operations = [
    ]
