# Generated by Django 4.2.7 on 2025-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clean_otp_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, default=None, editable=False, help_text='Temporary 6-digit code', max_length=6, null=True, verbose_name='OTP Code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='OTP Created At'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_verified',
            field=models.BooleanField(default=False, editable=False, verbose_name='OTP Verified'),
        ),
    ]
