# Generated by Django 4.2.7 on 2025-11-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20251114_1223'),
    ]

    operations = [
    ]
