# Generated by Django 4.2.7 on 2025-11-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20251114_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrcapplication',
            name='father_full_name',
            field=models.CharField(default='Not provided', max_length=200),
        ),
        migrations.AddField(
            model_name='nrcapplication',
            name='mother_full_name',
            field=models.CharField(default='Not provided', max_length=200),
        ),
        migrations.AddField(
            model_name='nrcapplication',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload your passport-size photo', null=True, upload_to='photos/applicants/'),
        ),
    ]
