# Generated by Django 4.2.7 on 2025-11-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_nrcapplication_nrc_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrcapplication',
            name='district',
            field=models.CharField(default='Not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='nrcapplication',
            name='father_district',
            field=models.CharField(default='Not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='nrcapplication',
            name='mother_district',
            field=models.CharField(default='Not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='nrcapplication',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
