# Generated by Django 4.2.7 on 2025-11-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_nrcapplication_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrcapplication',
            name='replacement_reason',
            field=models.TextField(blank=True, help_text='Reason for NRC replacement'),
        ),
    ]
